### ISSUE TITLE
info domains won't work.

### ISSUE THREAD

**Issue by Wanabo** [CHERTS/linux-scripts#1]
domain-check.sh
info domains returns always unknown. Perhaps another whois is needed.

**Comment by cherts** [comment]
what domain you check?

**Comment by Wanabo** [comment]
For example webcare.info

**Comment by cherts** [comment]
Fixed, see commit https://github.com/CHERTS/linux-scripts/commit/7d0ab6c8d4da1971a47f7469e9563abef4b8e217

**Comment by Wanabo** [comment]
Thanks! :+1: 
.info domains are working OK now.

Please compare your your version with this version, https://gist.github.com/mrrcollins/9a668109fa8a97f9fb90#file-domain-check
Your version reports numbers for registrar. The other version reports names for registrar.

```
Domain                              Registrar         Status   Expires     Days Left
----------------------------------- ----------------- -------- ----------- ---------
abcd.com                      151               Valid    15-may-2016   33
```

```
Domain                              Registrar         Status   Expires     Days Left
----------------------------------- ----------------- -------- ----------- ---------
abcd.com                      PSI-USA, INC. DBA Valid    15-may-2016   33
```

I think registrar names are nicer.

**Comment by Wanabo** [comment]
Found another problem with .org domains.

```
Domain                              Registrar         Status   Expires     Days Left
----------------------------------- ----------------- -------- ----------- ---------
people.org                          Unknown           Unknown  Unknown     Unknown
```

Second result is from, https://gist.github.com/mrrcollins/9a668109fa8a97f9fb90#file-domain-check

```
Domain                              Registrar         Status   Expires     Days Left
----------------------------------- ----------------- -------- ----------- ---------
people.org                          1API GmbH         Valid    25-may-2016   43
```

**Comment by cherts** [comment]
Fixed, see commit https://github.com/CHERTS/linux-scripts/commit/abff91d522d4c5973c63c6d58a12e3d4bdfac719

**Comment by cherts** [comment]
Fixed .me domain, see commit https://github.com/CHERTS/linux-scripts/commit/dd9b309728cf77e6ffdd5a300e1d2c7f9b8496ee

**Comment by Wanabo** [comment]
All is working OK! :+1: 
Good to see some one is actively maintaining this script.
