### ISSUE TITLE
Getting 'unknown' for all domains

### ISSUE THREAD

**Issue by galonge** [CHERTS/linux-scripts#4]
Hello, when i run this shell script on ubuntu terminal. i get 'unknown' status for Status, Expires and Days left.

**Comment by cherts** [comment]
Hi,
tell me which script and with what parameters you run?

**Comment by galonge** [comment]
copied the script to my Desktop, 
then ran 
`domain-check-2.sh -d google.com`
from that directory on the terminal .

**Comment by galonge** [comment]
I ran the 'domain-check.sh script'.

**Comment by cherts** [comment]
I fixed this script, please, download the new version
https://raw.githubusercontent.com/CHERTS/linux-scripts/master/dns/domain-check.sh
