### ISSUE TITLE
nginx-remove-vhost.sh - socket after removal

### ISSUE THREAD

**Issue by andchir** [CHERTS/linux-scripts#5]
Спасибо Вам за скрипты!
Тут по-моему есть ошибка:
https://github.com/CHERTS/linux-scripts/blob/master/nginx/nginx-remove-vhost.sh#L195
После перезагрузки то, что нет сокета, это не должно быть ошибкой, а наоборот нормальное состояние (т.к. конфиг уже удален).

**Comment by cherts** [comment]
Да, вы права.
Исправил d8ae1efe0731865b052f25e75b99c2b26a93f4c4 и 88f965997358f30e3f92101a6faef03bc779ec32
Спасибо.
