### ISSUE TITLE
Полезные скрипты для linux по категориям

### ISSUE THREAD

**Issue by symba4u** [CHERTS/linux-scripts#7]

**Comment by cherts** [comment]
Добрый день.
Идея интересная, но есть ложка дегтя
1. Боюсь этих категорий будет совсем немного. На вскидку это dns, database, web, monitoring, virtualization и наверно все. Причем где-то будет куча скриптов, а где-то как в virtualization - один.
2. Есть скрипты которые вообще непонятно к какой категории отнести.
3. Многие скрипты упоминаются в разных статьях у меня в блоге и не только у меня и если что-то поменять, то получим кучу мертвых ссылок на сайтах.
